version: '3'
services:

  nodered:
    image: nodered/node-red-docker
    networks:
    - microservicesnet
    environment:
    - SERVICE_NAME=node-red
    ports:
    - "1880:1880"
    volumes:
    - ${PWD}/nodered/runtime:/root/.node-red
    command: /usr/local/bin/node-red -v flows.json

  mosquitto:
    image: eclipse-mosquitto
    networks:
    - microservicesnet
    environment:
    - SERVICE_NAME=mosquitto
    volumes:
    - ${PWD}/mosquitto/runtime:/etc/mosquitto
    ports:
    - "1883:1883"
    - "9883:9883"

networks:
  microservicesnet:
    driver: overlay
